apiVersion: v1
kind: ConfigMap
metadata:
   name: licence
   namespace: {{ .Release.Namespace | quote }}
data:
   license: |
    FIPS=1
    SalesForce Connector=1
    ServiceNow Connector=1
    analytics=1
    api_visual_mapper=1
    apiportal=1
    company=Axway
    deployment_type=docker
    expires=Mon, 31 May 2021 16:52:15 GMT
    license_id=TEMP
    mcafee=1
    name=Axway
    sdkgenerator=1
    unrestricted=1
    version=7.7
    # SIGNATURE: 1680af45f73ec6f2c51647bd2c228e9a59f24a930eb84e99fb8a9e303a6b41ed
    # SIGNATURE: e6f286e5735d8fb02bcf305775b8d7a3d30938e6797ea8964f1363156fe9791d
    # SIGNATURE: db023b62515ba8e44a46f9857bc39fe2e9b6a9b0e4838aa9fe4db7504270b384
    # SIGNATURE: 8753b14072c692f7278d80f7a54f5ce8a1b1ad5ef9dd3c212004c3bd6c0e2d1b
    # SIGNATURE: d983ee4b2d50337f9edb42f1f596bd5326d0ee0aa8761300d8be8f3d1d663fa5
    # SIGNATURE: 5e7a7b91f43a98c219632b254de5afe981083d3f727864735a11f7fb934a4dd3
    # SIGNATURE: c74520a47d1053b78b0402544a0619d350ae5bc724ac1548b40c760a1188d943
    # SIGNATURE: 9ffab6e8af1aec569f77d19e453152b9fb3f6a9ae882fa61c061b1aa0231bf40
